### ISSUE TITLE
Snapping apps to one side of the screen leaves you unable to snap them to the other side

### ISSUE THREAD

**Issue by ferbivore** [zst123/MultiWindowSidebar#2]
Steps to reproduce:
1. Open an app from the sidebar, snapping it to either side of the screen.
2. Optionally, open other apps - the bug is reproducible as long as the first app doesn't get closed by the OS.
3. Try to snap the first app again from the sidebar, but to the opposite side.

What happens: the app is foregrounded in its original position.
What should probably happen: the app should be foregrounded _and_ snapped to the new position.

This looks related to [this XHaloFloatingWindow bug](https://github.com/zst123/XHaloFloatingWindow/issues/17) - it seems that when asked to open an already-open app, XHalo simply foregrounds it instead of reopening it in floating mode or moving the window.

**Comment by zst123** [comment]
It is unrelated to the XHFW bug you linked. It is fixed as of this commit.
https://github.com/zst123/XHaloFloatingWindow/commit/e33f4a4b55c296662ab59ca650ddbdc486033468
